version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  rebase-strategy: disabled
